const reliefData = {
    Monday: {
        classA: {
            period1: null,
            period2: null,
            period3: null,
            period4: null,
            period5: null,
            period6: null,
            period7: null,
            period8: null,
            period9: null,
        },
        classB: {
            period1: null,
            period2: null,
            period3: null,
            period4: null,
            period5: null,
            period6: null,
            period7: null,
            period8: null,
            period9: null,
        },
        classC: {
            period1: null,
            period2: null,
            period3: null,
            period4: null,
            period5: null,
            period6: null,
            period7: null,
            period8: null,
            period9: null,
        },
        classD: {
            period1: null,
            period2: null,
            period3: null,
            period4: null,
            period5: null,
            period6: null,
            period7: null,
            period8: null,
            period9: null,
        },
        classE: {
            period1: null,
            period2: null,
            period3: null,
            period4: null,
            period5: null,
            period6: null,
            period7: null,
            period8: null,
            period9: null,
        },
        classF: {
            period1: null,
            period2: null,
            period3: null,
            period4: null,
            period5: null,
            period6: null,
            period7: null,
            period8: null,
            period9: null,
        },
    },
    Tuesday: {
        classA: {
            period1: null,
            period2: null,
            period3: null,
            period4: null,
            period5: null,
            period6: null,
            period7: null,
            period8: null,
            period9: null,
        },
        classB: {
            period1: null,
            period2: null,
            period3: null,
            period4: null,
            period5: null,
            period6: null,
            period7: null,
            period8: null,
            period9: null,
        },
        classC: {
            period1: null,
            period2: null,
            period3: null,
            period4: null,
            period5: null,
            period6: null,
            period7: null,
            period8: null,
            period9: null,
        },
        classD: {
            period1: null,
            period2: null,
            period3: null,
            period4: null,
            period5: null,
            period6: null,
            period7: null,
            period8: null,
            period9: null,
        },
        classE: {
            period1: null,
            period2: null,
            period3: null,
            period4: null,
            period5: null,
            period6: null,
            period7: null,
            period8: null,
            period9: null,
        },
        classF: {
            period1: null,
            period2: null,
            period3: null,
            period4: null,
            period5: null,
            period6: null,
            period7: null,
            period8: null,
            period9: null,
        },
    },
    Wednesday: {
        classA: {
            period1: null,
            period2: null,
            period3: null,
            period4: null,
            period5: null,
            period6: null,
            period7: null,
            period8: null,
            period9: null,
        },
        classB: {
            period1: null,
            period2: null,
            period3: null,
            period4: null,
            period5: null,
            period6: null,
            period7: null,
            period8: null,
            period9: null,
        },
        classC: {
            period1: null,
            period2: null,
            period3: null,
            period4: null,
            period5: null,
            period6: null,
            period7: null,
            period8: null,
            period9: null,
        },
        classD: {
            period1: null,
            period2: null,
            period3: null,
            period4: null,
            period5: null,
            period6: null,
            period7: null,
            period8: null,
            period9: null,
        },
        classE: {
            period1: null,
            period2: null,
            period3: null,
            period4: null,
            period5: null,
            period6: null,
            period7: null,
            period8: null,
            period9: null,
        },
        classF: {
            period1: null,
            period2: null,
            period3: null,
            period4: null,
            period5: null,
            period6: null,
            period7: null,
            period8: null,
            period9: null,
        },
    },
    Thursday: {
        classA: {
            period1: null,
            period2: null,
            period3: null,
            period4: null,
            period5: null,
            period6: null,
            period7: null,
            period8: null,
            period9: null,
        },
        classB: {
            period1: null,
            period2: null,
            period3: null,
            period4: null,
            period5: null,
            period6: null,
            period7: null,
            period8: null,
            period9: null,
        },
        classC: {
            period1: null,
            period2: null,
            period3: null,
            period4: null,
            period5: null,
            period6: null,
            period7: null,
            period8: null,
            period9: null,
        },
        classD: {
            period1: null,
            period2: null,
            period3: null,
            period4: null,
            period5: null,
            period6: null,
            period7: null,
            period8: null,
            period9: null,
        },
        classE: {
            period1: null,
            period2: null,
            period3: null,
            period4: null,
            period5: null,
            period6: null,
            period7: null,
            period8: null,
            period9: null,
        },
        classF: {
            period1: null,
            period2: null,
            period3: null,
            period4: null,
            period5: null,
            period6: null,
            period7: null,
            period8: null,
            period9: null,
        },
    },
    Friday: {
        classA: {
            period1: null,
            period2: null,
            period3: null,
            period4: null,
            period5: null,
            period6: null,
            period7: null,
            period8: null,
            period9: null,
        },
        classB: {
            period1: null,
            period2: null,
            period3: null,
            period4: null,
            period5: null,
            period6: null,
            period7: null,
            period8: null,
            period9: null,
        },
        classC: {
            period1: null,
            period2: null,
            period3: null,
            period4: null,
            period5: null,
            period6: null,
            period7: null,
            period8: null,
            period9: null,
        },
        classD: {
            period1: null,
            period2: null,
            period3: null,
            period4: null,
            period5: null,
            period6: null,
            period7: null,
            period8: null,
            period9: null,
        },
        classE: {
            period1: null,
            period2: null,
            period3: null,
            period4: null,
            period5: null,
            period6: null,
            period7: null,
            period8: null,
            period9: null,
        },
        classF: {
            period1: null,
            period2: null,
            period3: null,
            period4: null,
            period5: null,
            period6: null,
            period7: null,
            period8: null,
            period9: null,
        },
    },
};
